# Generated by Django 5.2.6 on 2025-09-26 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Groceries', 'Groceries'), ('Leisure', 'Leisure'), ('Electronics', 'Electronics'), ('Utilities', 'Utilities'), ('Clothing', 'Clothing'), ('Health', 'Health'), ('Others', 'Others')], max_length=100)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
